#!/usr/bin/env python3
"""Generates the HQ master ROMs (run in rtl/sound: python3 gen_roms.py)

hq_limiter_rom.sv - the compressive part of the soft limiter curve,
  f(d) = span * (1 - exp(-d / span)) for d = |x| - knee, 1025 points
  over d in [0, 2) FS, Q0.28 (1.0 = full scale).
  knee = 24576 / 32768, span = (32000 - 24576) / 32768.

hq_comp_rom.sv - the compressor gain T / p for a peak p above the threshold
  T = 0.7071 FS (-3 dBFS): p normalized to m * 2^e, m in [1, 2), indexed by
  the 10 bits after the leading one, entry = T / m at the bin centre, Q1.31.
"""
import math

SPAN = (32000 - 24576) / 32768
THRESHOLD = 0.7071


def rom(name, width, values, comment):
    abits = (len(values) - 1).bit_length()
    lines = [f"// Generated by gen_roms.py - do not edit ({comment})",
             f"module {name}", "(", "    input  wire        clk,",
             f"    input  wire [{abits - 1}:0] addr,", f"    output reg  [{width - 1}:0] q", ");", "",
             f"reg [{width - 1}:0] rom [0:{len(values) - 1}];", "initial begin"]
    lines += [f"    rom[{i}] = {width}'d{v};" for i, v in enumerate(values)]
    lines += ["end", "", "always @(posedge clk) q <= rom[addr];", "", "endmodule", ""]
    with open(f"{name}.sv", "w") as f:
        f.write("\n".join(lines))


lim = [round(SPAN * (1 - math.exp(-2.0 * i / 1024 / SPAN)) * (1 << 28)) for i in range(1025)]
rom("hq_limiter_rom", 28, lim + [lim[-1]] * (2048 - len(lim)), "soft limiter curve")

comp = [round(THRESHOLD / (1 + (i + 0.5) / 1024) * (1 << 31)) for i in range(1024)]
rom("hq_comp_rom", 32, comp, "compressor gain T / m")
